"""add price_product to products

Revision ID: 1ab4a2ef86f6
Revises: 54abca02bcf2
Create Date: 2026-04-29 17:20:59.324513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ab4a2ef86f6'
down_revision: Union[str, Sequence[str], None] = '54abca02bcf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_alerts', sa.Column('price_product', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_alerts', 'price_product')
    # ### end Alembic commands ###
