"""create stock alerts table

Revision ID: 54abca02bcf2
Revises: 
Create Date: 2026-04-29 00:21:22.357827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54abca02bcf2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('customer_phone', sa.String(length=20), nullable=False),
    sa.Column('customer_email', sa.String(length=255), nullable=True),
    sa.Column('accepts_marketing', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('requested_quantity', sa.Integer(), server_default='1', nullable=False),
    sa.Column('external_product_id', sa.String(length=100), nullable=False),
    sa.Column('variation_id', sa.String(length=100), nullable=True),
    sa.Column('variation_name', sa.String(length=255), nullable=True),
    sa.Column('is_notified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_alerts_customer_phone'), 'stock_alerts', ['customer_phone'], unique=False)
    op.create_index(op.f('ix_stock_alerts_external_product_id'), 'stock_alerts', ['external_product_id'], unique=False)
    op.create_index(op.f('ix_stock_alerts_id'), 'stock_alerts', ['id'], unique=False)
    op.create_index(op.f('ix_stock_alerts_is_notified'), 'stock_alerts', ['is_notified'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_alerts_is_notified'), table_name='stock_alerts')
    op.drop_index(op.f('ix_stock_alerts_id'), table_name='stock_alerts')
    op.drop_index(op.f('ix_stock_alerts_external_product_id'), table_name='stock_alerts')
    op.drop_index(op.f('ix_stock_alerts_customer_phone'), table_name='stock_alerts')
    op.drop_table('stock_alerts')
    # ### end Alembic commands ###
